### ISSUE TITLE
Duplicate of closed issue #96

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#113]
Hey There,

B23/24 did not fix #96 - please reinvestigate if you can.... :(

**Comment by dezil** [comment]
@DraksterAU I also had this issue on my server it is because plugin manager is very outdated there are other plugin mangers out there use a different one

removing plugin manager stopped all this spam for me

**Comment by DraksterAU** [comment]
@dezil I do not have plugin manager installed.... I have LegendsQuest installed.

**Comment by DraksterAU** [comment]
@Robotia Any chance you could take another swing at this? :)

**Comment by Robotia** [comment]
Have you tried BL30?

**Comment by DraksterAU** [comment]
@Robotia Trying now

**Comment by DraksterAU** [comment]
@Robotia BL30 still comes up with the below. NOTE this comes up without Pwp installed also, I tested.
```

Could not pass event PlayerInteractEvent to LegendQuest v1.9.7
org.bukkit.event.EventException
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.30]
        at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.30]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.30]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1614.30]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:238) [ForgeEventFactory.class:1.7.10-1614.30]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick2(TileActivator.java:434) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick(TileActivator.java:401) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:217) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:176) [TileActivator.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2531) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:637) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:967) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2233) ~[?:?]
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2227) ~[?:?]
        at me.sablednah.legendquest.listeners.SkillLinkEvents.onInteract(SkillLinkEvents.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
        ... 17 more

```

**Comment by DraksterAU** [comment]
Created issue on the LQ GitHub too... https://github.com/Sablednah/LegendQuest/issues/3

**Comment by DraksterAU** [comment]
@Robotia  This appears to be caused by the autonomous activator item. We have them running on timers to automatically reboot failed computers throughout the server when they fail.

**Comment by Robotia** [comment]
Hmm ok I will see about this

**Comment by DraksterAU** [comment]
@Robotia This issue causes massive lag for players, even if the (10?) activator items we have that turn on once a minute are slowed down to once per 5.
We had to go back to KCauldron this morning after performance complaints (I rarely play and it seemed fine to use thermos at first glance... but after 24hrs the guys were pretty mad at me lol)

**Comment by DraksterAU** [comment]
Upon further testing @Robotia It appears cauldron contains something after B185 KCauldron that makes several items (including a StargateTech2 personal shield) unusable.

It also creates the same amount of lag as later versions of KCauldron... this might not be related to the Activator problems.

Looks like I'm stuck on B185.

**Comment by Robotia** [comment]
@DraksterAU I just released B32, try it please? :smile:

**Comment by DraksterAU** [comment]
@Robotia Do you believe this will fix the lag? And maybe the items that stopped working in thermos?? I'm talking about b28 too :/

**Comment by Robotia** [comment]
@DraksterAU With the TileActivators, yes I believe it will

**Comment by DraksterAU** [comment]
@Robotia Wonderful.
Ill do some testing offline... there are performance issues (and items stopping working) that need to be resolved before our server can come back to thermos :(

**Comment by DraksterAU** [comment]
@Robotia This is not fixed in B32 man.

**Comment by Robotia** [comment]
Fixed by https://github.com/TCPR/Thermos/commit/4df81b910d10b686959c27d542818f9e5e134cb1 for sure
