### ISSUE TITLE
Energy Bazooka - Blood Magic Crash

### ISSUE THREAD

**Issue by tyler2k15** [TCPR/Thermos#115]
``java.lang.ExceptionInInitializerError
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.getEntity(CraftEntity.java:176)
	at net.minecraft.entity.Entity.getBukkitEntity(Entity.java:1967)
	at net.minecraft.world.World.addEntity(World.java:1770)
	at net.minecraft.world.World.func_72838_d(World.java:1715)
	at WayofTime.alchemicalWizardry.common.items.EnergyBazooka.func_77659_a(EnergyBazooka.java:100)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:185)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:385)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:824)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: [Dropper]
	at java.util.UUID.fromString(UUID.java:194)
	at thermos.entity.CustomProjectileEntity.<clinit>(CustomProjectileEntity.java:31)
	... 17 more``

The above crash happens after upgrading to B25, but does not occur on b24
{When shooting at another player}

**Comment by iKaneki-Ken** [comment]
Can confirm this, just attempted to use it. Except it causes a different crash.

http://pastebin.com/SpyDeUDy

**Comment by tyler2k15** [comment]
IS that when you shoot it in general or when you shoot an entity/player? The crash my server received was from shooting at a player

**Comment by iKaneki-Ken** [comment]
When I shoot it in general.

**Comment by Robotia** [comment]
It's a Bukkit plugin issue, will try to fix tonight

**Comment by AppleObsession** [comment]
java.lang.ExceptionInInitializerError
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.getEntity(CraftEntity.java:176)
	at net.minecraft.entity.Entity.getBukkitEntity(Entity.java:1967)
	at net.minecraft.world.World.addEntity(World.java:1770)
	at net.minecraft.world.World.func_72838_d(World.java:1715)
	at matteroverdrive.items.weapon.PhaserRifle.spawnProjectile(PhaserRifle.java:260)
	at matteroverdrive.items.weapon.PhaserRifle.onServerFire(PhaserRifle.java:230)
	at matteroverdrive.entity.monster.EntityRangedRogueAndroidMob.attackEntityWithRangedAttack(EntityRangedRogueAndroidMob.java:210)
	at matteroverdrive.entity.ai.EntityAIPhaserBoltAttack.manageShooting(EntityAIPhaserBoltAttack.java:180)
	at matteroverdrive.entity.ai.EntityAIPhaserBoltAttack.func_75246_d(EntityAIPhaserBoltAttack.java:145)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:582)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2064)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36)
	at matteroverdrive.entity.monster.EntityRangedRogueAndroidMob.func_70636_d(EntityRangedRogueAndroidMob.java:119)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1897)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41)
	at net.minecraft.world.World.func_72866_a(World.java:2677)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:808)
	at net.minecraft.world.World.func_72870_g(World.java:2626)
	at net.minecraft.world.World.func_72939_s(World.java:2426)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:637)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:962)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: [Dropper]
	at java.util.UUID.fromString(UUID.java:194)
	at thermos.entity.CustomProjectileEntity.<clinit>(CustomProjectileEntity.java:31)

We are also getting this error and crash on the Same server that Tyler2k15 posted

**Comment by tyler2k15** [comment]
After doing some more testing on the Revenge of the C-Team pack (empty plugins folder) mod pack equipped with Thermos, we found the following to be true:

All ranged weapons from blood magic cause the same crash (as well as range spells )

Ranged androids from MatterOverdrive cause the crash as well

All other means of ranged projectiles seem to function as expected.

**Comment by Robotia** [comment]
Fixed by cc0b9aa6d80ae572c828739077409a3ad3a62468

**Comment by tyler2k15** [comment]
I can confirm this issue has been resolved in Build 27
