### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec

### ISSUE THREAD

**Issue by alicheek** [TCPR/Thermos#136]
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:25)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more

No idea why this is happening but trying to use your thermos system but im getting this when starting the script

**Comment by Robotia** [comment]
You need to re download the libraries:
https://github.com/TCPR/Thermos/releases/download/25/Thermos-1.7.10-1614.25-libraries.zip

Unzip that into your server's directory

**Comment by Yive** [comment]
http://tcpr.github.io/Thermos/install

**Comment by Yive** [comment]
wow, that ninja

**Comment by Robotia** [comment]
Heh

**Comment by alicheek** [comment]
thanks guys is working now :)
