### ISSUE TITLE
[Bug] Applied Energistics 2 - Spatial Pylons not working.

### ISSUE THREAD

**Issue by Loonacy** [TCPR/Thermos#150]
When trying to put together the multiblock pylons, they're supposed to turn from red to purple to indicate when they're ready.  When using Thermos, after placing multiple pylon blocks the first block will turn purple, but the remaining blocks will stay red.
If i then try to use the pylon through the Spatial IO Port, the server throws the following exception:

```
java.lang.ClassCastException: thermos.BlockUpdateEntry cannot be cast to net.minecraft.world.NextTickListEntry
        at appeng.spatial.CachedPlane.<init>(CachedPlane.java:161)
        at appeng.spatial.StorageHelper.swapRegions(StorageHelper.java:222)
        at appeng.items.storage.ItemSpatialStorageCell.doSpatialTransition(ItemSpatialStorageCell.java:175)
        at appeng.tile.spatial.TileSpatialIOPort.call(TileSpatialIOPort.java:146)
        at appeng.hooks.TickHandler.processQueue(TickHandler.java:280)
        at appeng.hooks.TickHandler.onTick(TickHandler.java:242)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_524_TickHandler_onTick_TickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:875)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675)
        at java.lang.Thread.run(Thread.java:745)
```

The server continues running without problems, but the pylon never finishes validating.  I restarted the server with plain Forge and the pylon worked without issue.

**Comment by Robotia** [comment]
Another issue with the block updates tracker that will be fixed ~ Friday
