### ISSUE TITLE
Build 33 errors?

### ISSUE THREAD

**Issue by Cracks777** [TCPR/Thermos#184]
[06:20:52] [Server thread/WARN]: java.lang.NullPointerException
[06:20:52] [Server thread/WARN]: 	at java.util.ArrayList.<init>(Unknown Source)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.func_72920_a(WorldServer.java:864)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:404)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:219)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:397)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:543)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:265)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:821)
[06:20:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:674)
[06:20:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Cracks777** [comment]
console spams those lines about 30 times or so on startup along with alot of these,

[06:20:27] [PaperSpigot - Lighting Thread/WARN]: Biome ID is out of bounds: 151372, defaulting to 0 (Ocean)

**Comment by NEXUS2345** [comment]
Can you please give us your spigot.yml and a modlist if you are using mods.

**Comment by Cracks777** [comment]
it was a fresh install? no mods no plugins

**Comment by NEXUS2345** [comment]
I will reiterate the first thing I asked for. Can you please give us your spigot.yml.

**Comment by Cracks777** [comment]
and ill say it again, it was a fresh install and was auto generated?

**Comment by Cracks777** [comment]
to reproduce, download latest version, build 33, install latest libraries, start server with no files, it auto generates the files and those errors are in the console?

**Comment by spannerman79** [comment]
Perhaps not all java source 8 code was removed.  Try re-adding `-noverify` back into your launch options.

*I haven't tested that build personally nor looked at the commits - just throwing a thought out there*

**Comment by Cracks777** [comment]
never mind its still doing it?

**Comment by Cracks777** [comment]
fixed in b34

**Comment by Cracks777** [comment]
and opis appears to be working again.

**Comment by Robotia** [comment]
Woo

**Comment by tyler2k15** [comment]
What version of opis @cracks @robotia

**Comment by Cracks777** [comment]
1.3.1

**Comment by tyler2k15** [comment]
So it doesn't need the KC fix or anything? Just regular Mobius Core works?

**Comment by cracks** [comment]
Hi  

Somehow my github username (@cracks) has been added to your conversation. It looks like @cracks777 is the person who should be on the thread.

**Comment by Cracks777** [comment]
https://github.com/Gamealition/Opis/releases/tag/1.3.1

 Mobius Core is included with this one. works with the latest build
