### ISSUE TITLE
[Caused by Async Lighting] [Crash] GalactiCraft - Exception generating new chunk

### ISSUE THREAD

**Issue by vadimyer** [TCPR/Thermos#185]
I think I got an issue with GC again, after upgrading from Thermos 28 to 32. Earlier it was a crash like "Generating new chunk..." that wasn't actually mod's issue, and it was fixed (I believe) in both Thermos & KC. But since upgrading to Thermos 32 this is the first time I got this kind of crash, happening in asteroids dimension:

```
---- Minecraft Crash Report ----
// You're mean.

Time: 3/1/16 2:39 PM
Description: Exception generating new chunk

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids.generateSkylightMap(ChunkProviderAsteroids.java:801)
	at micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids.func_73154_d(ChunkProviderAsteroids.java:536)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:241)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:199)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:167)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:305)
	at net.minecraft.world.World.func_72964_e(World.java:754)
	at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:79)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_301_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:987)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids.generateSkylightMap(ChunkProviderAsteroids.java:801)
	at micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids.func_73154_d(ChunkProviderAsteroids.java:536)

-- Chunk to be generated --
Details:
	Location: 24842,125550
	Position hash: 106697725176430
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:241)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:199)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:167)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:305)
	at net.minecraft.world.World.func_72964_e(World.java:754)
	at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:79)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_301_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:987)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: ca.tcpr:Thermos:1.7.10-1614.32
	Plugins: WorldEdit, JoinCommand, Skript, OpenInv, ChunkFixer, ClearLag, AutoMessage, iPAddressViewer, WorldBorder, LokiBlockerLite, BanManager, WorldGuard, AutoSaveWorld, MultiWorld, RedstoneClockDetector, Setblock, MachineGuard_Reloaded, iConomy, PermissionsEx, SQLibrary, AnimalProtect, CustomHelp, ReactionRewards, Vault, HideStream, Prism, MyWarp, ChestShop, ShoppingCartReloaded, MultiHome, ColorMe, NoobProtector, Essentials, BattleTracker, BattleArena, Scavenger, ProtocolLib, PayDay, EssentialsProtect, ModFixNG, SuperVanish, ArenaSpleef, EssentialsSpawn
	Disabled Plugins: 
	Operating System: Linux (amd64) version 3.16.0-4-amd64
	Java Version: 1.8.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 566561728 bytes (540 MB) / 3662151680 bytes (3492 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 2 total; -Xmx12G -Xverify:none
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (Thermos.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (Thermos.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	IC2{2.2.814-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.814-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.12} [BuildCraft] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.12} [BC Builders] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.12} [BC Transport] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.12} [BC Energy] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.12} [BC Silicon] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.12} [BC Robotics] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.12} [BC Factory] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenters-Blocks-3.3.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft-1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	cmd{1.4} [Custom Music Discs] (Custom Music Discs-1.4 Server.jar) 
	UCHIJAAAA	endercore{1.7.10-0.0.1.13_alpha} [EnderCore] (EnderCore-1.7.10-0.0.1.13_alpha.jar) 
	UCHIJAAAA	EventHelper{1.4} [EventHelper] (EventHelper-1.4.jar) 
	UCHIJAAAA	ExtrabiomesXL{3.16.3} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.3.jar) 
	UCHIJAAAA	Forestry{4.0.10.39} [Forestry for Minecraft] (forestry_1.7.10-4.0.10.39.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.437.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.437.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	GraviSuiteReloaded{1.7.10-0.9.1} [GraviSuiteReloaded] (GraviSuite_Reloaded-1.7.10-0.9.1.jar) 
	UCHIJAAAA	IC2CA{1.14.5.06} [IndustrialCraft 2 Combo Armors] (ic2ca-1.7.10-1.14.5.06.jar) 
	UCHIJAAAA	IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2] (IC2NuclearControl-2.2.5a.jar) 
	UCHIJAAAA	IronChest{6.0.41.729} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	RedstoneArsenal: -[1.7.10]1.1.1-89
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: mail, agricraft, enderio, erebus, extrautilities, growthcraft, harvestcraft, immersiveengineering, magicalcrops, natura, plantmegapack, witchery
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 34 / 100; [GCEntityPlayerMP['tbbm7'/1597, l='world', x=2797.20, y=63.00, z=1562.40](tbbm7 at 2797.2045098712783,63.0,1562.40365132843), GCEntityPlayerMP['KoZaK'/2938, l='world', x=2787.46, y=76.00, z=1341.75](KoZaK at 2787.4558239733165,76.0,1341.750727515677), GCEntityPlayerMP['Luch'/5330, l='world', x=3545.31, y=65.00, z=-1480.57](Luch at 3545.3059861573497,65.0,-1480.5736215875088), GCEntityPlayerMP['Busya'/46116, l='world', x=2547.70, y=9.00, z=-7457.54](Busya at 2547.699999988079,9.0,-7457.541703293992), GCEntityPlayerMP['Madery'/184365, l='world', x=2168.57, y=57.00, z=5157.66](Madery at 2168.56540428388,57.0,5157.664733318772), GCEntityPlayerMP['cCTPAXx'/203564, l='world', x=-1118.03, y=68.00, z=-3724.70](cCTPAXx at -1118.0279495953093,68.0,-3724.699999988079), GCEntityPlayerMP['RoronoaZoro'/217460, l='world', x=5918.85, y=74.00, z=7401.56](RoronoaZoro at 5918.849350464425,74.0,7401.556114096977), GCEntityPlayerMP['EnoTFapun'/238275, l='world', x=1463.75, y=59.00, z=1299.53](EnoTFapun at 1463.751130533788,59.0,1299.5267685351657), GCEntityPlayerMP['Frait'/244164, l='DIM-28', x=-1349.01, y=91.60, z=7129.95](Frait at -1349.0093055782813,91.59757376118651,7129.947644819841), GCEntityPlayerMP['mecs'/259896, l='world', x=1759.69, y=70.00, z=-8820.04](mecs at 1759.6900778116894,70.0,-8820.040067012402), GCEntityPlayerMP['MrNs'/322245, l='world', x=2334.25, y=68.03, z=-516.84](MrNs at 2334.245242232479,68.02899517112189,-516.8430782032206), GCEntityPlayerMP['crafter87'/347595, l='world', x=2167.06, y=7.00, z=4660.60](crafter87 at 2167.063658262135,7.0,4660.601675282842), GCEntityPlayerMP['krakun'/362632, l='world', x=3034.00, y=69.00, z=1270.93](krakun at 3033.996416473566,69.0,1270.927445697286), GCEntityPlayerMP['NeKiT'/364230, l='world', x=-3605.71, y=93.50, z=8487.86](NeKiT at -3605.7131521519605,93.5,8487.85814010236), GCEntityPlayerMP['MrAd'/377222, l='world', x=2836.39, y=93.00, z=3486.42](MrAd at 2836.3889942418737,93.0,3486.420707160624), GCEntityPlayerMP['Chicony'/351985, l='world', x=2837.84, y=93.00, z=3487.66](Chicony at 2837.8436164334653,93.0,3487.661415029971), GCEntityPlayerMP['Redfish'/388743, l='world', x=5752.08, y=90.00, z=-4126.07](Redfish at 5752.08154459379,90.0,-4126.072274346373), GCEntityPlayerMP['HamadMC'/392044, l='world', x=7777.18, y=87.00, z=1041.66](HamadMC at 7777.18024395783,87.0,1041.6645192207875), GCEntityPlayerMP['Michael'/7615, l='world', x=5881.87, y=72.00, z=7465.01](Michael at 5881.873761667087,72.0,7465.007383965148), GCEntityPlayerMP['CMETANKA'/400208, l='world', x=3020.71, y=70.00, z=1471.36](CMETANKA at 3020.70985511591,70.0,1471.3617458974882), GCEntityPlayerMP['KanYouTan'/417864, l='world', x=-6998.30, y=78.00, z=6935.84](KanYouTan at -6998.300000011921,78.0,6935.837782229657), GCEntityPlayerMP['Dimalike'/427308, l='world', x=1281.50, y=5.00, z=1351.63](Dimalike at 1281.4997133814295,5.0,1351.6273510323044), GCEntityPlayerMP['EvgenZver4ik'/427348, l='world', x=-2105.43, y=92.00, z=3653.90](EvgenZver4ik at -2105.429964916594,92.0,3653.900889673178), GCEntityPlayerMP['epic145'/432912, l='world', x=2426.46, y=70.00, z=1015.27](epic145 at 2426.4622563839666,70.0,1015.2657219848002), GCEntityPlayerMP['KpoT'/288193, l='world', x=-1354.12, y=59.00, z=2941.56](KpoT at -1354.1186231105676,59.0,2941.5573849707785), GCEntityPlayerMP['Nemezko'/436683, l='world', x=7777.28, y=87.00, z=1024.91](Nemezko at 7777.276127140156,87.0,1024.906445261743), GCEntityPlayerMP['dimzoid'/439186, l='world', x=-1358.70, y=65.00, z=2952.70](dimzoid at -1358.699999988079,65.0,2952.699999988079), GCEntityPlayerMP['piratka'/247133, l='DIM-30', x=397992.25, y=70.17, z=2008663.97](piratka at 397992.2485432691,70.17091447023941,2008663.9686470656), GCEntityPlayerMP['KaineXk1ng'/447249, l='world', x=-5918.97, y=80.00, z=-5956.19](KaineXk1ng at -5918.969190763063,80.0,-5956.193956594079), GCEntityPlayerMP['JuRIc'/418466, l='DIM-30', x=397454.94, y=110.17, z=2008704.06](JuRIc at 397454.9383434797,110.17157836043586,2008704.0596336636), GCEntityPlayerMP['croh'/455550, l='world', x=-6220.05, y=68.00, z=2011.56](croh at -6220.048910688797,68.0,2011.557741370046), GCEntityPlayerMP['AHOHIM'/442193, l='world', x=-8022.70, y=59.00, z=941.74](AHOHIM at -8022.699999988079,59.0,941.7426308972838), GCEntityPlayerMP['Rest0r'/460092, l='world', x=3106.08, y=63.00, z=439.08](Rest0r at 3106.0808075385435,63.0,439.07910781304713), GCEntityPlayerMP['Foxy02'/461424, l='world', x=2231.90, y=95.00, z=-1823.96](Foxy02 at 2231.9006253146185,95.0,-1823.9583047094318)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

If this is not Thermos's issue, sorry then.

P.S. Can anybody advise a bash script that will restart the server properly in an event of crash? Right now I got spigot.yml crash-restart set to true, AWS plugin also set to true. But nothing of them recovers the server from such a crash ._.

**Comment by Robotia** [comment]
```bash
while :
do
java -d64 -server -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m  -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms8G -Xmx12G -noverify -XX:hashCode=5 -Dfile.encoding=UTF-8 -jar Thermos.jar nogui --log-strip-color
sleep 2
done

```

**Comment by Robotia** [comment]
And I looked at the Galacticraft code, I do not believe this is being caused by Thermos

**Comment by vadimyer** [comment]
@Robotia Thanks for the script!
@rradfast please >_<

**Comment by Yive** [comment]
It's recommended to remove `-d64 -server` from the script.

**Comment by Cracks777** [comment]
@Yive how come?

**Comment by Yive** [comment]
Both of those parameters were made default in java 7 so pretty much pointless to have them in your script, @Cracks777

**Comment by Cracks777** [comment]
is it the same for java 8?

**Comment by Yive** [comment]
Most likely

**Comment by spannerman79** [comment]
Nope your wrong @Yive

http://docs.oracle.com/javase/7/docs/technotes/tools/windows/java.html

http://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html

(Using mobile chrome you can find the Linux ones yourself)

**Comment by radfast** [comment]
@vadimyer this crash is similar to this: https://github.com/micdoodle8/Galacticraft/issues/2066

It looks to me like MrTJP core is the cause (or one of the ProjectRed mods it supports?).  I don't understand why it is running a fresh chunkgen inside ```mrtjp.core.world.BlockUpdateHandler$.onTick```.

More generally - as with some other problems you have posted - the problem may be related to tick end code being run prematurely - I mean while some other part of the tick is still processing.  Please think carefully about whether you have config settings, mods or Bukkit plugins which are forcing tick ends, maybe to try to keep the TPS high or prevent lag?

I understand that the crash is visible in Galacticraft but I do not think Galacticraft is the **cause** of this crash.  We are generating a chunk here in the same way as many other mods, or vanilla Minecraft.  Our code works in standard Forge, and also, apparently, without MrTJP core.  It is totally reasonable for us to be running a block lighting update during worldgen code (it's actually an optimisation in our code, reducing the lighting updates that would normally occur from world.setBlock() - compare this with the vanilla chunkgen).

**Comment by DraksterAU** [comment]
`use-async-lighting: true `
Try setting this to false in spigot.yml

**Comment by Robotia** [comment]
Asynchronous lighting can be disabled in spigot.yml config: `use-async-lighting:false` @radfast @vadimyer

**Comment by Robotia** [comment]
A fix is slated for B45 which should automatically use regular lighting in chunks that are provided by mods, i.e. in this case `ChunkProviderAsteroids`.
