### ISSUE TITLE
Exception getting block type in world

### ISSUE THREAD

**Issue by K1ltu** [TCPR/Thermos#203]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/fPtMRuGs
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/SJjLCv3a
**Explanation of issue:**
after generating a new world just explore

the server that this is running on is more then fast enough to generate vanilla chunks at regular flight speed the chunks are generating instantly however it crashes with this

net.minecraft.util.ReportedException: Exception getting block type in world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:962) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.RuntimeException: Decoration took longer than 10 seconds!
        at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:109) ~[aia.class:?]
        at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339) ~[ahu.class:?]
        at net.minecraft.world.biome.BiomeGenHills.func_76728_a(BiomeGenHills.java:46) ~[aid.class:?]
        at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:426) ~[aqz.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.generator.NormalChunkGenerator.func_73153_a(NormalChunkGenerator.java:57) ~[NormalChunkGenerator.class:1.7.10-1614.42]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:423) ~[ms.class:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1191) ~[apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:307) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:213) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:181) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:319) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:755) ~[ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:681) ~[ahb.class:?]
        at net.minecraft.world.gen.feature.WorldGenMinable.func_76484_a(WorldGenMinable.java:76) ~[ase.class:?]
        at net.minecraft.world.biome.BiomeDecorator.func_76795_a(BiomeDecorator.java:351) ~[aia.class:?]
        at net.minecraft.world.biome.BiomeDecorator.func_76797_b(BiomeDecorator.java:370) ~[aia.class:?]
        at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:138) ~[aia.class:?]
        at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:129) ~[aia.class:?]
        at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339) ~[ahu.class:?]
        at net.minecraft.world.biome.BiomeGenHills.func_76728_a(BiomeGenHills.java:46) ~[aid.class:?]
        at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:426) ~[aqz.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.generator.NormalChunkGenerator.func_73153_a(NormalChunkGenerator.java:57) ~[NormalChunkGenerator.class:1.7.10-1614.42]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:423) ~[ms.class:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1191) ~[apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:307) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:213) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:181) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:319) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:755) ~[ahb.class:?]
        at net.minecraft.world.SpawnerAnimals.func_151350_a(SpawnerAnimals.java:38) ~[aho.class:?]
        at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:137) ~[aho.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:257) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:945) ~[MinecraftServer.class:?]
**How to recreate this issue:**
just fly around

**Modpack Name:** *(Only if public)*

**Mods Installed:**
opis 1.3.1 mapless

**Plugins Installed:**
None

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos Build 42

**Forge Version:**

**Comment by K1ltu** [comment]
Would like to add i have not modifyed any configs i was beginning the evaluation process to see if it would work on my production servers

**Comment by Razorskills** [comment]
Dude.. http://pastebin.com/
For your crash log

**Comment by tyler2k15** [comment]
I can verify this is an issue for me as well. 
https://gist.github.com/tyler2k15/b3e462765e9dd8d9114b

**Comment by tyler2k15** [comment]
I have reverted to Build 39 for the time being which is on all our production servers @k1ltu

**Comment by Robotia** [comment]
Fixed in 44.
