### ISSUE TITLE
[Crash] B45 Exception in server tick loop

### ISSUE THREAD

**Issue by Isolonice** [TCPR/Thermos#219]
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.gen.ChunkProviderServer.func_73241_b(ChunkProviderServer.java:127)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1102)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:532)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:856)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Bogdan-G** [comment]
full crash-log pls

**Comment by Isolonice** [comment]
http://pastebin.com/fUWrMhUR
