### ISSUE TITLE
[Server thread/ERROR]: "Silently" catching entity tracking error

### ISSUE THREAD

**Issue by vadimyer** [TCPR/Thermos#252]
Hi, I got this kind of errors spamming in console sometimes.

```
[14:03:56] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:278) [mn.class:?]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:158) [mn.class:?]
	at net.minecraft.world.WorldManager.func_72703_a(WorldManager.java:28) [mp.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1854) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1126) [mt.class:?]
	at net.minecraft.world.World.addEntity(World.java:1844) [ahb.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:653) [ForgeHooks.class:1.7.10-1614.49]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:164) [add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:498) [mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:857) [nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:233) ~[mn.class:?]
	... 18 more
```

1614.49.

**Comment by Robotia** [comment]
Fix has been slated for 50

**Comment by linkinkov** [comment]
Same for me
Wait for fix

**Comment by Robotia** [comment]
Fixed in B50.
