### ISSUE TITLE
BattleTowers Crash...

### ISSUE THREAD

**Issue by Zilacon** [TCPR/Thermos#281]
**Explanation of issue:**
World generates, battle towers "attempt" to generate, server crashes.

**How to recreate this issue:**
Place Battletowers into thermos server, run for several hours running around like a mad man generating chunks, eventually crash.

````
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 3/31/16 10:33 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at atomicstryker.battletowers.common.WorldGenHandler.flushCurrentPosListToFile(WorldGenHandler.java:321)
	at atomicstryker.battletowers.common.WorldGenHandler.generate(WorldGenHandler.java:76)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:472)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1206)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:907)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: ca.tcpr:Thermos:1.7.10-1614.53
	Plugins: WorldEdit, EmptyWorldGenerator, Essentials, LoginSecurity, GroupManager, DeletePlayerData, ConsoleScheduler, WorldBorder, SpawnJoin, Votifier, WorldGuard, MultiWorld, AlwaysDay, AsyncWorldEdit, KaisRandomTP, StopProxy, Vault, TekkitCustomizer, Prism, EssentialsSpawn, MassiveCore, LegendaryMessages, EnjinMinecraftPlugin, Smelter, ChestShop, MCBans, Resurrection, GriefPreventionPlus, RegionForSale, APOCPayday2, SilkSpawners, Legendchat, Factions
	Disabled Plugins: 
	Operating System: Linux (amd64) version 2.6.32-573.22.1.el6.x86_64
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 849875000 bytes (810 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 24 total; -Xms2048m -Xmx2048m -XX:ReservedCodeCacheSize=256m -XX:NewRatio=4 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=4 -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=25 -XX:+UseFastEmptyMethods -XX:+UseAdaptiveGCBoundary -XX:+UseCompressedOops -XX:UseSSE=3 -XX:ParallelGCThreads=1 -XX:+UseCodeCacheFlushing -XX:+UseFastAccessorMethods -XX:+UseBiasedLocking -Xverify:none -XX:+AggressiveOpts -XX:+UseNUMA -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (AA.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (AA.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJAAAA	fusionutil{0.1} [FusionUtil] ([1.7.10]FusionUtil-0.1.0.jar) 
	UCHIJAAAA	aiimprovements{0.0.1.19} [AI Improvements] (AIImprovements-1.7.10-0.0.1b19-dev.jar) 
	UCHIJAAAA	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14-core.jar) 
	UCHIJAAAA	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.114-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	nevermine{2.3} [AdventOfAscension] (AoA-2.4.B.jar) 
	UCHIJAAAA	AquaTweaks{1.0} [AquaTweaks] (AquaTweaks-1.7.10-1.0.jar) 
	UCHIJAAAA	mod_AsyncWorldEdit_Injector{2.1.0} [AsyncWorldEdit Injector] (AsyncWorldEditInjector.jar) 
	UCHIJAAAA	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (THAUMCRAFT-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (NATURA-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UCHIJAAAA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BIBLIOWOODS[BIOMESOPLENTY][V1.9].jar) 
	UCHIJAAAA	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BIBLIOWOODS[NATURA][V1.5].jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14-transport.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) 
	UCHIJAAAA	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UCHIJAAAA	fc-dummy{0} [fc-dummy] (fastcraft-1.22-ctest22.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.573} [Forbidden Magic] (Forbidden Magic-1.7.10-0.573.jar) 
	UCHIJAAAA	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) 
	UCHIJAAAA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJAAAA	heartdrop{1.3.2} [Heart Drop] (HeartDrop-1.7.10-1.3.2.jar) 
	UCHIJAAAA	kloudspacekloudgear{1.7.10-1.2.0} [HexxitGear] (HexxitGear-1.7.10-1.2.0.jar) 
	UCHIJAAAA	HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar) 
	UCHIJAAAA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4} [JourneyMap] (journeymap-1.7.10-5.1.4-unlimited.jar) 
	UCHIJAAAA	legendgear{2.b.2.1} [LegendGear 2] (legendgear-1.7.10-2.b.2.1.jar) 
	UCHIJAAAA	lootbags{1.8.1} [Loot Bags] (LootBags-1.7.10-1.8.1.jar) 
	UCHIJAAAA	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCHIJAAAA	magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury] (magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar) 
	UCHIJAAAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.1.1.2} [Minecraft Comes Alive] (MCA-1.7.10-5.1.1.2-universal.jar) 
	UCHIJAAAA	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJAAAA	MSM3{3.0.0d} [More Swords 3] (MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) 
	UCHIJAAAA	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	nTweaks{1.7.10} [nTweaks] (nTweaks-1.7.10-SNAPSHOT.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1-snapshot-438.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1-snapshot-708.jar) 
	UCHIJAAAA	fodc{1.6.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.6.1.jar) 
	UCHIJAAAA	desertcraft{1.7.2b} [Pam's DesertCraft] (Pam's DesertCraft 1.7.10a.zip) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	simplerecipes{1.7.10a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.7.10a.jar) 
	UCHIJAAAA	primitivemobs{1.0} [Primitive Mobs] (PRIMITIVEMOBS-1.0C-1.7.10.jar) 
	UCHIJAAAA	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHIJAAAA	xreliquary{1.2} [Reliquary] (Reliquary-1.2.257.jar) 
	UCHIJAAAA	Sanguimancy{1.7.10-1.1.9-29} [Sanguimancy] (SANGUIMANCY-1.7.10-1.1.9-29.jar) 
	UCHIJAAAA	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
	UCHIJAAAA	Tails{1.7.10-1.4.1a} [Tails] (Tails-1.7.10-1.4.1a.jar) 
	UCHIJAAAA	TaintedMagic{1.1.6.4} [Tainted Magic] (TaintedMagic-1.1.6.4.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
	UCHIJAAAA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJAAAA	TickProfiler{1.7.10} [TickProfiler] (TickProfiler-1.7.10.42.jar) 
	UCHIJAAAA	tinkersdefense{1.3a} [Tinkers' Defense] (tinkersdefense-1.3.4a.jar) 
	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAA	TSteelworks{1.7.10-1.1.2} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.2-20.jar) 
	UCHIJAAAA	VanillaPlus{1.4.0} [VanillaPlus] (VanillaPlus-1.7.10-1.4.0.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@6a37fc5e) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@58fe138a) returned non-null result: 0
	CoFHCore: -[1.7.10]3.1.2-325
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	NetherOres: -[1.7.10]2.3.1-22
	TConstruct Environment: Environment healthy.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Hardcore Ender Expansion: CAUTION! Ars Magica 2 is not supported by HEE, if the crash is caused by a conflict of the two mods, it will very likely not be possible to fix.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 3 / 50; [EntityPlayerMP['Clutch_Cabbage'/113908, l='Resource', x=-27.24, y=64.00, z=-297.61](Clutch_Cabbage at -27.23883694607612,64.0,-297.61108410988857), EntityPlayerMP['Sickllama'/116912, l='Resource', x=-30.13, y=64.00, z=-298.29](Sickllama at -30.13460347072889,64.0,-298.2901274368197), EntityPlayerMP['dave1821'/125271, l='S-1', x=912.32, y=88.49, z=-735.74](dave1821 at 912.3215223627915,88.49064318920136,-735.7441818700958)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)
````

I am not sure if this is a issue with BT or Thermos but figured id find out by posting it here.

**Comment by iKaneki-Ken** [comment]
Wow man, you sure are finding a lot of mod incompatibilities. xD

**Comment by Zilacon** [comment]
I can only assume its Thermos because this NEVER happens on single player. We tested this modpack for 2 months with BT on it and never got this crash until I setup a server for it.

**Comment by iKaneki-Ken** [comment]
No, you're right, it is a Thermos issue.
