### ISSUE TITLE
Assertion errors when using World Generator Plugin

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#292]
Ive got a weird one... I am getting assertion errors when trying to load the plugin, "Epic World Generator".

These do not appear to be related to the plugin, but more a security issue in Thermos.

Using B48 at the moment, but tested on 54.

```
[03:22:58] [Server thread/ERROR]: Error occurred while enabling EpicWorldGenerator v6.29-RELEASE (Is it up to date?)
java.lang.AssertionError
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:733) ~[TypeAdapters$EnumTypeAdapter.class:?]
        at com.google.gson.internal.bind.TypeAdapters$26.create(TypeAdapters.java:762) ~[TypeAdapters$26.class:?]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52) ~[CollectionTypeAdapterFactory.class:?]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
--
        at com.minelazz.epicworldgenerator.EpicConfigManager.a(Unknown Source) ~[?:?]
        at com.minelazz.epicworldgenerator.EpicWorldGenerator.onEnable(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.46]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.46]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.46]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1614.46]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1614.46]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:365) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:369) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

```

**Comment by DraksterAU** [comment]
Plugin Dev confirmed not a thermos issue.
