### ISSUE TITLE
Holographic Display bug [Thermos 17b]

### ISSUE THREAD

**Issue by linkinkov** [TCPR/Thermos#78]
[22:37:28] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.1.10
[22:37:28] [Server thread/WARN]: java.lang.NoSuchFieldException: d
[22:37:28] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:37:28] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.util.ReflectionUtils.putInPrivateStaticMap(ReflectionUtils.java:10)
[22:37:28] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_7_R4.NmsManagerImpl.registerCustomEntity(NmsManagerImpl.java:59)
[22:37:28] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_7_R4.NmsManagerImpl.setup(NmsManagerImpl.java:39)
[22:37:28] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onEnable(HolographicDisplays.java:148)
[22:37:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[22:37:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[22:37:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[22:37:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[22:37:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[22:37:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[22:37:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[22:37:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[22:37:28] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[22:37:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[22:37:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:37:28] [Server thread/INFO]: 
 
******************************************************
     HolographicDisplays was unable to register
     custom entities, the plugin will be disabled.
     Are you using the correct Bukkit version?
******************************************************

On 13r all work properly. I think its because you rename server.

**Comment by Robotia** [comment]
@linkinkov Try this: https://github.com/TCPR/Fixes/tree/master/HolographicDisplays

**Comment by linkinkov** [comment]
This version dont help me, anyway:
[22:59:38] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.1.10
[22:59:38] [Server thread/WARN]: java.lang.NoSuchFieldException: d
[22:59:38] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:59:38] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.util.ReflectionUtils.putInPrivateStaticMap(ReflectionUtils.java:10)
[22:59:38] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_7_R4.NmsManagerImpl.registerCustomEntity(NmsManagerImpl.java:59)
[22:59:38] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.nms.v1_7_R4.NmsManagerImpl.setup(NmsManagerImpl.java:39)
[22:59:38] [Server thread/WARN]: 	at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onEnable(HolographicDisplays.java:148)
[22:59:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[22:59:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[22:59:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[22:59:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[22:59:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[22:59:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[22:59:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[22:59:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[22:59:38] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[22:59:38] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[22:59:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:59:38] [Server thread/INFO]:

**Comment by Robotia** [comment]
@Yive I think it is the rename :/

**Comment by Yive** [comment]
I will look into this
