### ISSUE TITLE
Lighting Error

### ISSUE THREAD

**Issue by Time6628** [TCPR/Thermos#86]
Getting this error on the latest Thermos. Also, there are no players on the server when this happens.
```
[10:57:51] [PaperSpigot - Lighting Thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.RuntimeException: Missing
	at cpw.mods.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:238) ~[FMLServerHandler.class:1.7.10-1614.UNOFFICIAL]
	at cpw.mods.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:542) ~[FMLCommonHandler.class:1.7.10-1614.UNOFFICIAL]
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$8.selectNetworks(FMLOutboundHandler.java:225) ~[FMLOutboundHandler$OutboundTarget$8.class:1.7.10-1614.UNOFFICIAL]
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:1.7.10-1614.UNOFFICIAL]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:236) [SimpleNetworkWrapper.class:1.7.10-1614.UNOFFICIAL]
	at Reika.DragonAPI.Instantiable.IO.PacketPipeline.sendToServer(PacketPipeline.java:132) [PacketPipeline.class:?]
	at Reika.DragonAPI.Libraries.IO.ReikaPacketHelper.sendSoundPacket(ReikaPacketHelper.java:750) [ReikaPacketHelper.class:?]
	at Reika.DragonAPI.Libraries.IO.ReikaSoundHelper.sendSound(ReikaSoundHelper.java:156) [ReikaSoundHelper.class:?]
	at Reika.DragonAPI.Libraries.IO.ReikaSoundHelper.playSound(ReikaSoundHelper.java:152) [ReikaSoundHelper.class:?]
	at Reika.DragonAPI.Libraries.IO.ReikaSoundHelper.playSound(ReikaSoundHelper.java:132) [ReikaSoundHelper.class:?]
	at Reika.ChromatiCraft.Registry.ChromaSounds.playSound(ChromaSounds.java:114) [ChromaSounds.class:?]
	at Reika.ChromatiCraft.Registry.ChromaSounds.playSoundAtBlock(ChromaSounds.java:118) [ChromaSounds.class:?]
	at Reika.ChromatiCraft.Base.CrystalTypeBlock.ding(CrystalTypeBlock.java:59) [CrystalTypeBlock.class:?]
	at Reika.ChromatiCraft.Base.CrystalTypeBlock.ding(CrystalTypeBlock.java:63) [CrystalTypeBlock.class:?]
	at Reika.ChromatiCraft.Base.CrystalTypeBlock.ding(CrystalTypeBlock.java:55) [CrystalTypeBlock.class:?]
	at Reika.ChromatiCraft.Base.CrystalTypeBlock.func_149726_b(CrystalTypeBlock.java:36) [CrystalTypeBlock.class:?]
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:710) [apx.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:813) [ahb.class:?]
	at Reika.ChromatiCraft.World.CrystalGenerator.generate(CrystalGenerator.java:57) [CrystalGenerator.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.REPLACED_generateWorld(GameRegistry.java:137) [GameRegistry.class:1.7.10-1614.UNOFFICIAL]
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
	at farseek.util.Reflection$MethodValue$.apply$extension(Reflection.scala:59) [Reflection$MethodValue$.class:?]
	at farseek.core.ReplacedMethod.apply(MethodReplacer.scala:105) [Farseek-1.0.10.jar:?]
	at farseek.world.gen.ChunkGeneratorExtensions$.generateWorld(ChunkGeneratorExtensions.scala:19) [ChunkGeneratorExtensions$.class:?]
	at farseek.world.gen.ChunkGeneratorExtensions.generateWorld(ChunkGeneratorExtensions.scala) [ChunkGeneratorExtensions.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java) [GameRegistry.class:1.7.10-1614.UNOFFICIAL]
	at Reika.ChromatiCraft.Auxiliary.ChromaAux.interceptChunkPopulation(ChromaAux.java:65) [ChromaAux.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:451) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1187) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:305) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:200) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:168) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:317) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:752) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:678) [ahb.class:?]
	at net.minecraft.world.World.func_98179_a(World.java:3654) [ahb.class:?]
	at net.minecraft.world.World.updateLightByType(World.java:3785) [ahb.class:?]
	at net.minecraft.world.World$6.run(World.java:4866) [ahb$6.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
```

**Comment by Robotia** [comment]
DragonAPI is part of the problem: `    at Reika.DragonAPI.Instantiable.IO.PacketPipeline.sendToServer(PacketPipeline.java:132) [PacketPipeline.class:?]`

I am sorry but we do not support any of Reika's mods.

**Comment by Time6628** [comment]
Alright, thanks anyways :smile_cat:

**Comment by Robotia** [comment]
As far as I can tell, it deals with DragonAPI trying to control chunk generation. I suggest editing the cauldron.yml and seeing if you can disable the generator for ChromatiCraft (I think there should be one).
