### ISSUE TITLE
[Thermos 21] Error with /th tps

### ISSUE THREAD

**Issue by Esctogrillo** [TCPR/Thermos#91]
On /th tps:
![screenshot_1](https://cloud.githubusercontent.com/assets/14919996/12938690/08a87066-cf9e-11e5-95ff-c088092487ba.png)

Console:
```
[02:26:27] [Server thread/INFO]: Esctogrillo issued server command: /th tps
[02:26:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'th tps' in thermos.ThermosCommand(thermos)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[SimpleCommandMap.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1316) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1098) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at thermos.ThermosCommand.mean(ThermosCommand.java:171) ~[ThermosCommand.class:1.7.10-1614.UNOFFICIAL]
	at thermos.ThermosCommand.execute(ThermosCommand.java:100) ~[ThermosCommand.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.UNOFFICIAL]
	... 12 more
```

**Comment by Yive** [comment]
I've fixed this issue. I will be doing a few more edits before commit though.
