### ISSUE TITLE
Issue with PlayerInteractEvent

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Thermos#96]
Getting this everything I try to switch to Thermos from KCauldron...
Spams the console constantly... :(

```

[08:41:44] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to LegendQuest v1.9.7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1614.UNOFFICIAL]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:228) [ForgeEventFactory.class:1.7.10-1614.UNOFFICIAL]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick(TileActivator.java:407) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:217) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:176) [TileActivator.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2528) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:637) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2233) ~[?:?]
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2227) ~[?:?]
        at me.sablednah.legendquest.listeners.SkillLinkEvents.onInteract(SkillLinkEvents.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
        ... 15 more


```

**Comment by Robotia** [comment]
KCauldron is not the same thing as Thermos...

**Comment by DraksterAU** [comment]
Argh so many different alternatives..... Lol

**Comment by Robotia** [comment]
Should be fixed in B23, which will be released soon.

**Comment by DraksterAU** [comment]
@Robotia B23 & 24 did not fix this.

**Comment by iKaneki-Ken** [comment]
Uh. . . There are only 2 modded minecraft server softwares. This and KCauldron. .
